name: CI
on:
  push:
    branches:
      - main
      - "releases/**"
      - github_actions

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1
      - name: Poetry install
        run: poetry install --no-interaction
      - name: Pytest
        run: poetry run pytest
